# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mensagem.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(554, 177)
        Dialog.setStyleSheet("QDialog{\n"
"    background-color: rgb(240, 240, 240);\n"
"}")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 40, 131, 16))
        self.label.setStyleSheet("QLabel{\n"
"    font-size: 16px;\n"
"    font-family:Arial,Helvetica,sans-serif;\n"
"}")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(150, 29, 281, 31))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    border: none;\n"
"    \n"
"    padding-left: 10px;\n"
"    \n"
"    font-family:Arial,Helvetica,sans-serif;\n"
"    font-size: 17px;\n"
"\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 1px solid rgb(0, 120, 215);\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(150, 110, 161, 18))
        self.checkBox.setStyleSheet("QCheckBox{\n"
"    font-family:Arial,Helvetica,sans-serif;\n"
"    font-size: 15px;\n"
"    border: none;\n"
"    border: 1px soldi black;\n"
"}")
        self.checkBox.setIconSize(QtCore.QSize(16, 16))
        self.checkBox.setCheckable(True)
        self.checkBox.setObjectName("checkBox")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(330, 100, 91, 31))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(182, 182, 182);\n"
"    font-family:Arial,Helvetica,sans-serif;\n"
"\n"
"    font-size: 15px;\n"
"    border: none;\n"
"    border: 1px solid rgb(124, 124, 124);\n"
"}")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Insira mensagem:"))
        self.checkBox.setText(_translate("Dialog", "Mostrar caixa de erro"))
        self.pushButton.setText(_translate("Dialog", "Confirmar"))
